export const HISTORY_BACK = "HISTORY_BACK";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADVERTS_LOADED_SUCCESS = "ADVERTS_LOADED_SUCCESS";
export const ADVERTS_LOADED_FAILURE = "ADVERTS_LOADED_FAILURE";
export const ADVERTS_LOADED_REQUEST = "ADVERTS_LOADED_REQUEST";
export const UI_RESET_ERROR = "UI_RESET_ERROR";

export const ADVERT_LOADED_REQUEST = "ADVERT_LOADED_REQUEST";
export const ADVERT_LOADED_SUCCESS = "ADVERT_LOADED_SUCCESS";
export const ADVERT_LOADED_FAILURE = "ADVERT_LOADED_FAILURE";

export const ADVERT_DELETED_REQUEST = "ADVERT_DELETED_REQUEST";
export const ADVERT_DELETED_SUCCESS = "ADVERT_DELETED_SUCCESS";
export const ADVERT_DELETED_FAILURE = "ADVERT_DELETED_FAILURE";

export const ADVERT_CREATED_REQUEST = "ADVERT_CREATED_REQUEST";
export const ADVERT_CREATED_SUCCESS = "ADVERT_CREATED_SUCCESS";
export const ADVERT_CREATED_FAILURE = "ADVERT_CREATED_FAILURE";

export const TAGS_LOADED_REQUEST = "TAGS_LOADED_REQUEST";
export const TAGS_LOADED_SUCCESS = "TAGS_LOADED_SUCCESS";
export const TAGS_LOADED_FAILURE = "TAGS_LOADED_FAILURE";
